AWSTemplateFormatVersion: '2010-09-09'
Description: CodePipeline for Node.js Lambda Build Stage

Resources:
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: NodejsLambdaBuildProject
      Description: CodeBuild project for building Node.js Lambda application
      ServiceRole: !GetAtt CodeBuildServiceRole.Arn
      Artifacts:
        Type: CODEPIPELINE
        Packaging: ZIP
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/nodejs:16.0.0 # Or specify desired Node.js version
        EnvironmentVariables:
          - Name: NODE_ENV
            Value: production
      Source:
        Type: CODEPIPELINE
        BuildSpec: |
          version: 0.2
          phases:
            install:
              commands:
                - npm install
            build:
              commands:
                - npm test || true # Run tests, allow failure if needed
                - npm run build || true # If you have a build step (e.g., webpack, tsc)
                - # Ensure only necessary files are packaged for Lambda
                - # Example: cp -r src/* dist/
                - # For simple Node.js Lambda, often just package all source
          artifacts:
            files:
              - '**/*'
            base-directory: './'
            # Include files needed for Lambda deployment, e.g., 'index.js', 'package.json', 'node_modules/**'
            # For a simple Lambda, packaging the whole folder might be sufficient.
            # Adjust 'base-directory' and 'files' based on your project structure.

  CodeBuildServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: CodeBuildAccessPolicy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - s3:PutObject
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:GetBucketAcl
                  - s3:GetBucketLocation
                Resource: '*'
